#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION
#undef _XOPEN_SOURCE
#include <wget.h>
#include <convert.h>
#include <url.h>
#include <html-url.h>
